// The established renderer is a template-string view. Keep the locale layer
// deterministic and side-effect free while the UI is incrementally migrated
// to keyed copy. Longer phrases run first so short labels cannot corrupt them.
const ENGLISH_REPLACEMENTS = Object.freeze([
  ["要把这个项目连接到 Codex 吗？连接后，Harness 会为它准备必要的 Codex 项目和管理对话，可能会使用你的 Codex 额度。即使连接失败，当前项目也会保留。", "Connect this project to Codex? Harness will prepare the required Codex project and control conversations, which may use your Codex allowance. If connection fails, this Harness project remains intact."],
  ["新建项目不会自动连接 Codex。导入时也只会读取你选中的项目，不会翻看其他对话。", "Creating a project does not connect Codex. Import reads only the Codex project you select and never searches other conversations."],
  ["先保存项目名称和目标，之后再选择文件夹或连接 Codex。", "Save the project name and goal first. You can choose a folder or connect Codex later."],
  ["从你已经在 Codex 中建立的项目导入现有信息。", "Import existing information from a project you already created in Codex."],
  ["这里只会在 Harness 中保存项目资料，不会连接 Codex，也不会读取代码或历史记录。", "This saves project details in Harness only. It does not connect Codex or read code or conversation history."],
  ["如果找到多个相似项目，我们会让你选择，不会自动替你决定。", "If several projects look similar, Harness asks you to choose instead of guessing."],
  ["你可以选择一个现有的 Codex 项目。确认导入前，不会启动任何任务。", "Choose an existing Codex project. No task starts before you confirm the import."],
  ["没有检测到 Codex，但你仍然可以先新建项目", "Codex was not found, but you can still create a project first."],
  ["这里只保存名称和目标，不会连接 Codex，也不会读取代码或历史记录。", "This saves only the name and goal. It does not connect Codex or read code or conversation history."],
  ["普通任务结果到达后会等待人工审核；只有接受才推进 Project HEAD。", "Agent results wait for your review. Project progress changes only after you accept a result."],
  ["归档只改变 Harness 项目状态，不删除 Git、Codex 对话或原始归档。", "Archiving changes only the Harness project status. It does not delete Git data, Codex conversations, or archives."],
  ["置顶只影响 Harness 自己的窗口，不会抢焦点或影响其他 Agent。", "Always on top affects only the Harness window and never steals focus from other apps."],
  ["可选；按住 Ctrl/⌘ 可多选，任务会等前置任务验收后再启动。", "Optional. Hold Ctrl/⌘ to select several. The task waits until its prerequisites are accepted."],
  ["新建一个，或者从 Codex 带过来。", "Create a project or bring one in from Codex."],
  ["先建个项目吧", "Create your first project"],
  ["目前没有需要确认的结果", "No results need your review"],
  ["还没有任务", "No tasks yet"],
  ["新建一个清晰、可验收的工作单元。", "Create a clear, reviewable unit of work."],
  ["项目已经准备好，但 Codex 没有自动打开。你可以再试一次。", "The project is ready, but Codex did not open automatically. Try opening it again."],
  ["已经连接，但 Codex 没有打开", "Connected, but Codex did not open"],
  ["连接已经完成。请彻底退出 Codex Desktop 后重新打开，确认项目是否出现在侧栏。", "Connection is complete. Fully quit and reopen Codex Desktop, then confirm the project appears in the sidebar."],
  ["这一步没完成", "This step did not finish"],
  ["正在准备…", "Preparing…"],
  ["正在处理…", "Working…"],
  ["重新尝试", "Try again"],
  ["重新打开 Codex", "Open Codex again"],
  ["小助手", "Getting started"],
  ["选择方式后继续", "Choose an option to continue"],
  ["项目从哪里来？", "Where is this project coming from?"],
  ["从哪里开始？", "Where would you like to start?"],
  ["添加项目", "Add project"],
  ["新建项目", "Create project"],
  ["从 Codex 导入", "Import from Codex"],
  ["开始导入", "Start import"],
  ["项目名称（必填）", "Project name (required)"],
  ["项目文件夹（可选）", "Project folder (optional)"],
  ["现在不选也没关系", "You can choose this later"],
  ["你想完成什么？（可选）", "What would you like to accomplish? (optional)"],
  ["技术栈（可选）", "Tech stack (optional)"],
  ["需要注意的事项（可选）", "Notes and constraints (optional)"],
  ["每行一项", "One item per line"],
  ["Codex 项目名称", "Codex project name"],
  ["已找到 Codex", "Codex found"],
  ["没有检测到 Codex", "Codex not found"],
  ["项目来源", "Project source"],
  ["项目详情", "Project details"],
  ["关闭项目详情", "Close project details"],
  ["项目位置", "Project location"],
  ["编辑契约", "Edit project brief"],
  ["项目状态", "Project status"],
  ["当前 Objective", "Current objective"],
  ["打开项目目录", "Open project folder"],
  ["标记 Objective 已完成", "Mark objective complete"],
  ["切换 Objective", "Change objective"],
  ["打开最近对话", "Open recent conversation"],
  ["新建项目对话", "New project conversation"],
  ["连接 Codex", "Connect Codex"],
  ["刷新状态", "Refresh"],
  ["新对话", "New conversation"],
  ["进入 CTO", "Open CTO"],
  ["新建任务", "New task"],
  ["恢复项目", "Restore project"],
  ["筛选项目", "Filter projects"],
  ["名称 / 状态", "Name / status"],
  ["现在做什么", "Current objective"],
  ["任务已验收", "tasks accepted"],
  ["项目状态正常", "Project is healthy"],
  ["项目任务", "Project tasks"],
  ["任务列表", "Task list"],
  ["等待你的确认", "Waiting for your review"],
  ["拒绝结果", "Reject result"],
  ["退回修改", "Request changes"],
  ["接受并推进 HEAD", "Accept result"],
  ["拒绝导入", "Reject import"],
  ["重新盘点", "Refresh import"],
  ["接受并写入 Harness", "Accept import"],
  ["查看验收结果与证据", "Review checks and evidence"],
  ["验收结果", "Acceptance checks"],
  ["Agent 证据", "Agent evidence"],
  ["建议下一步", "Suggested next step"],
  ["没有建议下一步", "No next step suggested"],
  ["没有附加证据", "No additional evidence"],
  ["任务名称", "Task name"],
  ["工作流", "Workstream"],
  ["验收条件", "Acceptance criteria"],
  ["每行一条验收条件", "One acceptance check per line"],
  ["执行 Agent", "Agent"],
  ["会话策略", "Session policy"],
  ["上下文方式", "Context mode"],
  ["自动选择", "Automatic"],
  ["复用工作流", "Reuse workstream context"],
  ["自动工作流", "Automatic workstream context"],
  ["温会话", "Reusable session"],
  ["一次性会话", "One-time session"],
  ["优先级", "Priority"],
  ["指定 Section（可选）", "Section (optional)"],
  ["开始时自动按工作流选择", "Choose automatically when the task starts"],
  ["前置任务（可选）", "Prerequisite tasks (optional)"],
  ["暂无可依赖任务", "No available prerequisite tasks"],
  ["审核方式", "Review mode"],
  ["用户确认后推进（推荐）", "Wait for my approval (recommended)"],
  ["Review Agent 自动推进", "Review Agent accepts automatically"],
  ["创建任务", "Create task"],
  ["开始任务（注入 Codex）", "Start task with Codex"],
  ["开始任务", "Start task"],
  ["重试 Codex 回填", "Retry Codex import"],
  ["打开对话", "Open conversation"],
  ["打开项目入口", "Open project"],
  ["停止回填", "Stop import"],
  ["改派 Section", "Change section"],
  ["打开工作区", "Open workspace"],
  ["复制任务包", "Copy task packet"],
  ["提交结果", "Submit result"],
  ["补交结果", "Submit updated result"],
  ["停止", "Stop"],
  ["已写入项目进展", "Saved to project progress"],
  ["尚未填写验收条件", "No acceptance criteria yet"],
  ["自动 Section", "Automatic section"],
  ["等待前置：", "Waiting for prerequisites: "],
  ["Agent 运行态", "Agent run status"],
  ["进程已记录", "Process recorded"],
  ["打开运行归档", "Open run archive"],
  ["待整理", "Backlog"],
  ["可开始", "Ready"],
  ["进行中", "In progress"],
  ["已结束，待回写", "Finished, awaiting result"],
  ["等待用户在 Agent 中执行", "Waiting for user action in Agent"],
  ["待确认", "Awaiting review"],
  ["需修改", "Changes requested"],
  ["已完成", "Completed"],
  ["执行失败", "Failed"],
  ["等待用户操作", "Waiting for user action"],
  ["已停止", "Stopped"],
  ["已暂停", "Paused"],
  ["已阻塞", "Blocked"],
  ["已归档", "Archived"],
  ["普通", "Normal"],
  ["紧急", "Urgent"],
  ["高", "High"],
  ["低", "Low"],
  ["取消", "Cancel"],
  ["还没有可核对的官方 Codex Project。", "No official Codex Project is available to verify yet."],
  ["请完全退出 Codex Desktop 后重新打开，再核对侧栏。", "Fully quit and reopen Codex Desktop, then check the sidebar."],
  ["app-server 已返回该 Project；当前 Desktop 侧栏仍需一次完全退出后的冷启动核对。", "The app server returned this project. Fully quit and reopen Codex Desktop once to verify it in the sidebar."],
  ["Codex Desktop 已接受项目深链；CTO、Review 和后续任务会归入这个 Project。", "Codex Desktop accepted the project deep link. CTO, Review, and future task conversations will stay in this project."],
  ["已有官方 Project ID，但没有把它直接当作侧栏可见性证明。", "An official Project ID exists, but it is not treated as proof that the project appears in the sidebar."],
  ["旧任务未保存独立 thread，将按项目最近对话打开", "This older task has no dedicated thread; Harness will open the project's most recent conversation"],
  ["审核与回写由 Review Agent 自动完成，无需用户确认。", "The Review Agent handles review and write-back automatically; no manual approval is required."],
  ["原始 transcript 在模型上下文外独立归档，确认后才会合并到项目。", "The original transcript is archived outside model context and joins the project only after approval."],
  ["候选已通过结构化协议校验。", "The candidate passed structured-protocol validation."],
  ["普通任务结果到达后会等待人工审核；只有接受才推进 Project HEAD。", "Regular task results wait for your review. Project HEAD advances only after acceptance."],
  ["可在项目 Git 中添加 origin；本地状态不受影响", "Add an origin to the project Git repository; local state is unaffected"],
  ["点击右上角刷新以读取最近 PR / Issue（只读）。", "Refresh at the top right to load recent pull requests and issues (read-only)."],
  ["开始任务时会按 workstream 自动建立可复用 Section。", "Starting a task automatically creates a reusable Section for its workstream."],
  ["导入旧 Agent 会话后，这里只显示 hash、大小和来源索引。", "After importing an older Agent conversation, only its hash, size, and source index appear here."],
  ["CTO、Review 和后续任务对话会归入这个 Codex 项目。", "CTO, Review, and future task conversations belong to this Codex project."],
  ["状态与 JSONL 回放日志会在每次状态变更后原子写入。", "State and JSONL replay logs are written atomically after every state change."],
  ["Codex Project 已写入，但 Desktop 归组证据尚未完成。", "The Codex Project is recorded, but Desktop grouping still needs verification."],
  ["状态、上下文、Ledger 和事实索引均可读取", "State, context, ledger, and fact indexes are readable"],
  ["任务改派只更新后续调度归属，不会重跑已完成的任务；运行中的任务请先停止。", "Reassigning a task changes future routing only. Completed tasks do not rerun; stop a running task first."],
  ["主控 Section 只负责调配；这里创建一个可复用或一次性执行区。", "The control Section coordinates work only. Create a reusable or one-time execution area here."],
  ["这里保存长期事实；它会进入 CTO/Review 上下文和动态项目白皮书。", "This stores long-lived facts for CTO and Review context and the living project whitepaper."],
  ["只保存 Git 的 origin 地址；不会登录或上传代码。提交后可用本机 gh 读取 PR/Issue。", "This stores only the Git origin URL. It does not sign in or upload code. Your local gh CLI can then read pull requests and issues."],
  ["模板只填充目标、技术栈、约束和不重复的起始任务；已有内容不会删除。", "Templates add goals, tech stack, constraints, and non-duplicate starter tasks. Existing content is never deleted."],
  ["Harness 会在当前项目下创建一个独立对话，不会继续堆积旧的 resume 历史。", "Harness creates a separate conversation in this project instead of extending old resume history."],
  ["旧 Objective 会保留在历史中，并自动变为暂停或 superseded；项目同时只保留一个 active Objective。", "The old Objective stays in history and becomes paused or superseded. Each project keeps only one active Objective."],
  ["正常情况下结果由 Agent 自动回写并交给项目 Review Agent；这里保留人工补交入口，便于恢复异常运行。", "Normally the Agent writes results back to the project Review Agent automatically. This manual fallback helps recover interrupted runs."],
  ["这里创建一个可复用或一次性执行区。", "Create a reusable or one-time execution area here."],
  ["会在当前项目下创建一个独立对话，不会继续堆积旧的", "creates a separate conversation in this project instead of extending old"],
  ["空白项目可在这里绑定本地工作区", "Bind a local workspace to this blank project here"],
  ["例如：整理需求并完成第一个可验收任务", "For example: organize requirements and complete the first reviewable task"],
  ["例如：保持本地优先，不上传 transcript", "For example: stay local-first and never upload transcripts"],
  ["例如：讨论下一阶段架构", "For example: discuss the next architecture stage"],
  ["例如：完成跨 Agent 回写验收", "For example: validate cross-Agent write-back"],
  ["例如：我的第一个项目", "For example: My first project"],
  ["例如：前端迭代", "For example: Frontend iteration"],
  ["项目持续，Agent 轮换", "Persistent projects, replaceable Agents"],
  ["选择一种方式后继续。", "Choose an option to continue."],
  ["改派任务 Section", "Reassign task Section"],
  ["暂无可用 Section", "No available Section"],
  ["新建工作 Section", "Create work Section"],
  ["可复用 Section", "Reusable Section"],
  ["一次性 Section", "One-time Section"],
  ["默认 Agent", "Default Agent"],
  ["创建 Section", "Create Section"],
  ["Section 名称", "Section name"],
  ["项目契约", "Project brief"],
  ["项目目录", "Project folder"],
  ["项目目标", "Project goal"],
  ["待解决问题 / 阻塞", "Open questions / blockers"],
  ["保存契约", "Save brief"],
  ["连接 GitHub 远端", "Connect GitHub remote"],
  ["远端地址", "Remote URL"],
  ["远端名称", "Remote name"],
  ["保存远端", "Save remote"],
  ["套用项目模板", "Apply project template"],
  ["空白项目", "Blank project"],
  ["Web 应用", "Web app"],
  ["库 / SDK", "Library / SDK"],
  ["自动化工具", "Automation tool"],
  ["研究 / 原型", "Research / prototype"],
  ["应用模板", "Apply template"],
  ["记录工程决策", "Record engineering decision"],
  ["决策内容", "Decision"],
  ["理由（可选）", "Rationale (optional)"],
  ["保存决策", "Save decision"],
  ["新建项目对话", "New project conversation"],
  ["对话主题", "Conversation topic"],
  ["Codex Project 对话", "Codex Project conversation"],
  ["Claude Code（用户主动）", "Claude Code (user initiated)"],
  ["Hermes（用户主动）", "Hermes (user initiated)"],
  ["会话类型", "Conversation type"],
  ["可继续的温会话", "Reusable warm conversation"],
  ["一次性讨论", "One-time discussion"],
  ["创建并打开", "Create and open"],
  ["切换 Objective", "Change Objective"],
  ["新 Objective", "New Objective"],
  ["将当前 Objective 标记为 superseded", "Mark the current Objective as superseded"],
  ["提交 Agent 结果", "Submit Agent result"],
  ["结构化结果 JSON", "Structured result JSON"],
  ["送交审核", "Send for review"],
  ["即将写入的项目快照", "Project snapshot to be imported"],
  ["最新进展", "Latest progress"],
  ["未提供 checkpoint", "No checkpoint provided"],
  ["未提供分支", "No branch provided"],
  ["未命名任务", "Untitled task"],
  ["Review Agent 已通过", "Review Agent approved"],
  ["Review Agent 后台审核中", "Review Agent is reviewing in the background"],
  ["Codex 回填候选 · 等待你的确认", "Codex import candidate · waiting for your review"],
  ["Review Agent 自动审核中", "Review Agent is reviewing automatically"],
  ["本次候选包含：", "This candidate contains:"],
  ["基于 HEAD R", "Based on HEAD R"],
  ["Git 暂不可用", "Git unavailable"],
  ["正在等待仓库", "Waiting for repository"],
  ["当前分支", "Current branch"],
  ["项变更", " changes"],
  ["工作区干净", "Working tree clean"],
  ["领先", "Ahead"],
  ["落后", "Behind"],
  ["未设置上游", "No upstream"],
  ["个分支", " branches"],
  ["个标签", " tags"],
  ["检查于", "Checked"],
  ["工作区变更", "Working tree changes"],
  ["没有本地变更", "No local changes"],
  ["最近提交", "Recent commits"],
  ["还没有提交", "No commits yet"],
  ["没有 GitHub 远端", "No GitHub remote"],
  ["gh 已认证", "gh authenticated"],
  ["gh 未认证", "gh not authenticated"],
  ["仅显示远端", "Remote only"],
  ["更换远端", "Change remote"],
  ["最近 PR", "Recent pull requests"],
  ["最近 Issue", "Recent issues"],
  ["暂无可用数据", "No data available"],
  ["还没有工作 Section", "No work Sections yet"],
  ["还没有会话归档", "No conversation archives yet"],
  ["最近一次进展", "Latest progress"],
  ["进展轨迹", "Progress timeline"],
  ["个 checkpoint", " checkpoints"],
  ["下一步：", "Next: "],
  ["用户主入口", "Primary user entry"],
  ["上下文待发送", "Context ready to send"],
  ["上下文待生成", "Context not generated"],
  ["后台自动审核 · 上下文自动限长", "Automatic background review · bounded context"],
  ["后台运行", "Running in background"],
  ["PROJECT DETAILS", "PROJECT DETAILS"],
  ["持久化数据盘", "Persistent data store"],
  ["当前用户数据目录", "Current user data directory"],
  ["开发环境画像", "Development profile"],
  ["刷新开发环境画像", "Refresh development profile"],
  ["包管理器：", "Package manager: "],
  ["入口：", "Entry points: "],
  ["接入时会自动扫描常见入口", "Common entry points are detected automatically"],
  ["项目健康", "Project health"],
  ["需要关注", "Needs attention"],
  ["缺少：", "Missing: "],
  ["版本状态", "Version status"],
  ["刷新 Git", "Refresh Git"],
  ["远端协作", "Remote collaboration"],
  ["刷新 GitHub", "Refresh GitHub"],
  ["任务容器", "Task containers"],
  ["工程记忆", "Engineering memory"],
  ["决策", "Decisions"],
  ["还没有结构化决策", "No structured decisions yet"],
  ["审计", "Audit"],
  ["最近事件", "Recent events"],
  ["暂无事件", "No events yet"],
  ["无损存储", "Lossless storage"],
  ["会话归档", "Conversation archives"],
  ["桌面显示", "Desktop display"],
  ["面板置顶", "Always on top"],
  ["取消置顶", "Turn off always on top"],
  ["可用 Agent", "Available Agents"],
  ["无能力清单", "No capability list"],
  ["上下文容器", "Context containers"],
  ["还没有会话", "No conversations yet"],
  ["项目工具", "Project tools"],
  ["打开动态白皮书", "Open living whitepaper"],
  ["导入会话归档", "Import conversation archive"],
  ["查看归档目录", "Open archive folder"],
  ["导出项目包", "Export project bundle"],
  ["导入项目包", "Import project bundle"],
  ["归档项目", "Archive project"],
  ["暂停项目", "Pause project"],
  ["恢复运行", "Resume project"],
  ["归档项目状态", "Archive project status"],
  ["暂无可依赖任务", "No prerequisite tasks available"],
  ["项目列表", "Project list"],
  ["未命名 Objective", "Untitled Objective"],
  ["最新事件", "Latest event"],
  ["个 Agent 正在运行", " Agents running"],
  ["项结果待确认", " results awaiting review"],
  ["项", " items"],
  ["官方 Project 已创建 · 待冷启动核对", "Official Project created · cold-start check pending"],
  ["官方 Project 已确认 · 侧栏待核对", "Official Project confirmed · sidebar check pending"],
  ["官方 Project 已创建 · Desktop 已注册", "Official Project created · Desktop registered"],
  ["已记录官方 Project · 侧栏待核对", "Official Project recorded · sidebar check pending"],
  ["等待同步", "Waiting to sync"],
  ["排队中", "Queued"],
  ["启动 Agent", "Starting Agent"],
  ["分析中", "Analyzing"],
  ["执行中", "Executing"],
  ["执行命令", "Running command"],
  ["更新文件", "Updating files"],
  ["整理结果", "Preparing result"],
  ["等待审核", "Waiting for review"],
  ["通过", "Passed"],
  ["未通过", "Failed"],
  ["依赖", "Depends on"],
  ["等待前置：", "Waiting for prerequisites: "],
  ["目标", "Goal"],
  ["阻塞", "Blockers"],
  ["关闭", "Close"],
  ["保存改派", "Save reassignment"],
  ["读取", "Read"],
  ["模板", "Template"],
  ["讨论", "Discussion"],
  ["创建", "Create"],
  ["打开", "Open"],
  ["校验", "Verify"],
  ["正常", "Healthy"],
  ["刷新", "Refresh"],
  ["同步", "Sync"],
  ["官方", "Official"],
  ["项目", "Projects"],
  ["当前", "Current"],
  ["名称", "Name"],
  ["类型", "Type"],
  ["默认", "Default"],
  ["结果", "Result"],
  ["会话", "Conversations"],
  ["记录", "Record"],
  ["归档", "Archive"],
  ["置顶", "Pin"],
  ["新建", "New"],
  ["远端", "Remote"],
  ["暂无", "None"],
  ["未找到", "Not found"],
  ["已检测", "Detected"],
  ["已结束", "Finished"],
  ["个活动", " active"],
  ["个归档", " archives"],
  ["个事件", " events"],
  ["次", " times"],
  ["项目已准备好，但 Codex 没有自动打开。你可以再试一次。", "The project is ready, but Codex did not open automatically. Try again."],
  ["连接已经完成。请彻底退出 Codex Desktop 后重新打开，确认项目出现在侧栏。", "Connection is complete. Fully quit and reopen Codex Desktop, then confirm the project appears in the sidebar."],
  ["已经连接，请重新打开 Codex", "Connected. Reopen Codex"],
  ["已经连接，但 Codex 没有打开", "Connected, but Codex did not open"],
  ["打开错误日志", "Open error log"],
  ["当前界面没有这个控件；请先完成前置步骤。", "This control is not available yet. Complete the earlier step first."],
  ["检查完成", "Check complete"],
  ["现在没有正在进行的检查", "No check is running"],
  ["检查已停止，正在运行的任务不会受到影响", "Check stopped. Running tasks are unaffected"],
  ["检查已经结束", "The check has already finished"],
  ["Codex Project 与 CTO / Review 已创建并归组", "Codex Project, CTO, and Review were created and grouped"],
  ["官方 Project 已确认；请完全退出 Codex Desktop 后重开，再核对侧栏", "Official Project confirmed. Fully quit and reopen Codex Desktop, then check the sidebar"],
  ["Codex Project 已同步", "Codex Project synced"],
  ["面板已置顶", "Always on top enabled"],
  ["已取消置顶", "Always on top disabled"],
  ["已打开项目工作区；请在对应 Agent 中使用 Harness Skill", "Project workspace opened. Use the Harness Skill in the corresponding Agent"],
  ["无法打开工作区：", "Could not open workspace: "],
  ["未知错误", "Unknown error"],
  ["Codex 连接已建立", "Codex connection established"],
  ["已在文件夹中定位错误日志", "Error log revealed in its folder"],
  ["状态已手动刷新", "Status refreshed"],
  ["Git 状态已刷新", "Git status refreshed"],
  ["GitHub 状态已刷新", "GitHub status refreshed"],
  ["开发环境画像已刷新", "Development profile refreshed"],
  ["已打开动态项目白皮书", "Living project whitepaper opened"],
  ["无法打开白皮书：", "Could not open whitepaper: "],
  ["已打开项目目录", "Project folder opened"],
  ["无法打开项目目录：", "Could not open project folder: "],
  ["已打开归档目录", "Archive folder opened"],
  ["无法打开归档目录：", "Could not open archive folder: "],
  ["已打开该任务的原始运行归档", "Original run archive opened"],
  ["无法打开运行归档：", "Could not open run archive: "],
  ["归档校验通过", "Archive verified"],
  ["归档校验失败，请保留原始文件并检查磁盘", "Archive verification failed. Keep the original file and check the disk"],
  ["已取消导出", "Export cancelled"],
  ["项目包已导出", "Project bundle exported"],
  ["已取消导入", "Import cancelled"],
  ["项目包已导入", "Project bundle imported"],
  ["归档已存在，已复用内容对象", "Archive already exists; reused the content object"],
  ["会话已无损归档", "Conversation archived losslessly"],
  ["项目已归档，原始数据未删除", "Project archived; original data was not deleted"],
  ["项目已暂停", "Project paused"],
  ["项目已恢复运行", "Project resumed"],
  ["Objective 已归档为完成", "Objective archived as completed"],
  ["项目已恢复", "Project restored"],
  ["Section 已关闭", "Section closed"],
  ["Section 已归档", "Section archived"],
  ["Codex 项目回填已重新启动", "Codex project import restarted"],
  ["用户主动路径已准备，任务包已复制", "User-driven path prepared; task packet copied"],
  ["任务已开始，任务包已复制", "Task started; task packet copied"],
  ["任务已停止，项目状态已保存", "Task stopped; project state saved"],
  ["任务包已复制", "Task packet copied"],
  ["Codex 项目数据已审核并写入 Harness", "Codex project data reviewed and imported into Harness"],
  ["结果已接受，Project HEAD 已推进", "Result accepted; Project HEAD advanced"],
  ["已退回，点击任务可重新盘点 Codex Project", "Returned for changes. Open the task to refresh the Codex Project inventory"],
  ["结果已退回修改", "Result returned for changes"],
  ["导入候选已拒绝，原始 rollout 仍保留在归档", "Import candidate rejected; the original rollout remains archived"],
  ["候选结果已拒绝，原始结果仍保留在项目归档", "Candidate rejected; the original result remains in the project archive"],
  ["请先选择“新建项目”或“从 Codex 导入”", "Choose Create project or Import from Codex first"],
  ["请填写项目名称", "Enter a project name"],
  ["正在新建项目", "Creating project"],
  ["本地项目已创建；没有搜索历史或连接 Agent", "Local project created without searching history or connecting an Agent"],
  ["请填写 Codex 项目名称或简称", "Enter the Codex project name or short name"],
  ["已定位", "Located"],
  ["，Codex 项目回填已启动，完成后等待审核", "; Codex project import started and will wait for review"],
  ["任务已创建；尚未注入 Agent，请点击“开始任务”", "Task created but not sent to an Agent. Select Start task when ready"],
  ["请选择目标 Section", "Choose a target Section"],
  ["任务已改派到 Section", "Task reassigned to Section"],
  ["Section 已创建", "Section created"],
  ["项目契约已保存", "Project brief saved"],
  ["GitHub 远端已保存", "GitHub remote saved"],
  ["项目模板已应用", "Project template applied"],
  ["决策已记录", "Decision recorded"],
  ["项目新对话已打开", "New project conversation opened"],
  ["项目新对话已创建，请稍后重试打开", "New project conversation created. Try opening it again shortly"],
  ["Objective 已切换，旧目标保留在历史中", "Objective changed; the old objective remains in history"],
  ["候选结果已送交审核", "Candidate sent for review"],
  ["结果 JSON 无效", "Invalid result JSON"],
  ["会话归档完成", "Conversation archive complete"],
  ["正在归档", "Archiving"],
  ["启动失败", "Startup failed"],
  ["当前已记录", "Currently recorded"],
  ["切换到中文", "Switch to Chinese"],
  ["个成员对话（2+N）。", " member conversations (2+N)."],
  ["从 Codex 刷新项目", "Refresh project from Codex"],
  ["从 Codex 回填到此项目", "Import from Codex into this project"],
  ["约束 / 要求", "Constraints / requirements"],
  ["审核状态", "Review status"],
  ["尚未检测", "Not detected yet"],
  ["项任务", " tasks"],
  ["已关闭", "Closed"],
  ["可复用", "Reusable"],
  ["空闲", "Idle"],
  ["复用", "Reusable"],
  ["游标", "Cursor"],
  ["任务：", "Task: "],
  ["技术栈", "Tech stack"],
  ["例如：", "For example: "],
  ["标记", "Mark"],
  ["切换", "Change"],
  ["任务", "Task"],
]);

export function localizeAppHtml(html, locale = "zh-CN", protectedValues = []) {
  if (locale !== "en") return html;
  const tokens = [];
  let output = String(html);
  [...new Set(protectedValues.map((value) => String(value || "")).filter(Boolean))]
    .sort((left, right) => right.length - left.length)
    .forEach((value, index) => {
      const token = `__APH_USER_TEXT_${index}__`;
      if (output.includes(value)) {
        output = output.split(value).join(token);
        tokens.push([token, value]);
      }
    });
  output = ENGLISH_REPLACEMENTS
    .slice()
    .sort((left, right) => right[0].length - left[0].length)
    .reduce((result, [source, target]) => result.split(source).join(target), output);
  return tokens.reduce((result, [token, value]) => result.split(token).join(value), output);
}

export { ENGLISH_REPLACEMENTS };
